name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    env:
      CURRENT_BRANCH: master
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install
      - name: Lint the project
        run: yarn lint
      - name: Check code types
        run: yarn check-types
      - name: Build the project
        run: yarn build
      - name: Upload a build artifact to master
        if: ${{ contains(github.event.head_commit.message, 'bump version') }}
        run: |
          cp dist/instagram-login.js index.js
          git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --local user.name "${GITHUB_ACTOR}"
          git add index.js
          git commit -m 'ci: publish index.js'
          git push